### ISSUE TITLE
Documentation could improve a lot

### ISSUE THREAD

**Issue by dataf3l** [cenit-io/cenit#1423]
The documentation for the tools could improve significantly, particularly the aspect of connectors, flow, webhooks, algorithms and aspects related with the code applications. I don't think the current documentation is sufficient for a user to use the tool effectively, we had to download the source code in order to figure out the error messages.

**Comment by sanchojaf** [comment]
Hi @dataf3l you are complete right!

I did some update to `https://github.com/cenit-io/docs` but we need to continue doing a lot of improvement there.

I included in the readme of this project how is possible run locally. 

I think that could great create specific TODOs in this repo or do any other contributions there.
