### ISSUE TITLE
Error with Scheduler API actions

### ISSUE THREAD

**Issue by sanchojaf** [cenit-io/cenit#1441]
when we run the api that is supposed to retrieve the list of all the schedulers

using the example code provided

no schedulers are returned

even though, in the user interface we do have schedulers

Retrieve all existing ‘Schedulers’

```batch
curl -X GET \
     -H ‘X-User-Access-Key: ${user_access_key}’ \
     -H ‘X-User-Access-Token: ${user_access_token}’ \
     -H ‘Content-Type: application/json’ \
     -d ‘{“page”:1,“limit”:25,“order”:“id”}’ \
     ‘https://cenit.io/api/v2/setup/scheduler.json'
```

no workie.

returns empty

{“total_pages”:0,“current_page”:1,“count”:0,“schedulers”:[]}

as you can see in the screenshots, schedulers exist, but are not returned.

Hello again, I just ran into a new issue
 
we are trying to create a scheduler automatically

however, our ruby client code, which uses the example, fails when the JSON is invalid

we are using the exact same JSON which is stored in the database to represent an expression for the schedule
 
recently, it came to our attention, that the schedulers are validated using a schema validator

unfortunately, we don’t know what we are doing wrong, and the JSON validator is complaining that the incoming json is empty
 
this is the error:

elipes-MacBook-Pro:cenit_source a$ ack ‘JSON. Parser Error: A JSON text must at least contain two octets!’
 
 
this is our code:

 ```
post ‘/make_post’ do
    #name = @request_payload[“request”][“data”][“cedula”]
    #puts @request_payload
    user_access_key=‘XXXXXXX’
    user_access_token=‘XXXXXXX’
    begin
        response = RestClient::Request.execute(
            :url => “https://cenit.io/api/v2/setup/scheduler.json“,
            :method => ‘post’,
            :headers => {
                ‘content-type’ => ‘application/json’,
                ‘x-user-access-key’ => user_access_key,
                ‘x-user-access-token’ => user_access_token,
                ‘params’ => {“namespace”:“local”,“name”:“a”,“expression”:‘{“start_at”:“2017-05-10”,“end_at”:“2017-05-10”,“type”:“cyclic”,“cyclic_expression”:“1d”}‘,“activated”:“false”}
            }
        )

        puts JSON.parse(response.body)
    rescue => e
        puts e
        puts e.response
    end
    return ‘ok’
end
```

credentials elided for future archiving…

```
our libs

require ‘sinatra’
require ‘json’
require ‘pp’
require ‘rest-client’
```

we *are* using the default multi-tenant instance online

your server

the username is “julis1997lg@gmail.com”

we have been unable to create the scheduler instance, despite the fact we have tried different JSON alternatives, all the JSON examples we have provided, come directly from the user interface inside cenit.

the JSON SCHEMA doesn’t seem to like it, for some reason…

perhaps a bug?

we consistently get the same response

```
{“request_id”:“a9f298c0-4c38-40fd-9a7b-b48d36d3424d”,“code”:406,“summary”:“JSON. Parser Error: A JSON text must at least contain two octets!“}
```

**Comment by dataf3l** [comment]
Some additional information:
we were ABLE to create the schedulers, but the schedulers were not created using the example cenit code, but code found online for a HTTPS JSON POST request, basically, the examples in cenit don't work, neither nodejs nor ruby at least. they urlencode the information, instead of json.

this is the code that *did* work:

		uri = URI.parse('https://cenit.io/api/v2/setup/scheduler.json')
		https = Net::HTTP.new(uri.host, uri.port)
		https.use_ssl = true
		
		req = Net::HTTP::Post.new(uri.path, 
					{
						'Content-Type' => 'application/json',
						'x-user-access-key' => user_access_key,
						'x-user-access-token' => user_access_token})

		$EX = '{"start_at":"2017-05-10","end_at":"2017-05-10","type":"cyclic","cyclic_expression":"1d"}'
		req.body = '{"namespace":"local","name":"a90210","expression":'+$EX+',"activated":"false"}'
		res = https.request(req)
		puts "response #{res.body}"


I hope this helps solve the issue, which as I see it, is bad code examples.

**Comment by dataf3l** [comment]
Also, thank you for taking the time to review this issues, I honestly believe this will make the platform better.

**Comment by sanchojaf** [comment]
thank @dataf3l you feedback is helpful

**Comment by dataf3l** [comment]
I'm just doing my job.

**Comment by sanchojaf** [comment]
```bath
 curl -X POST \
     -H 'X-User-Access-Key: XXXXXX' \
     -H 'X-User-Access-Token: YYYYYY' \
     -H 'Content-Type: application/json' \
     -d '{"id":"sasa","namespace":"test","name":"a9021sds","_type":"","expression":{"start_at":"2017-05-10","end_at":"2017-05-10","type":"cyclic","cyclic_expression":"1d"},"activated":""}' \
     'https://cenit.io/api/v2/setup/scheduler.json' 
```

cURL work fine, if id: is not empty or if you remove the id.

Maybe we need to clarify that id is optional

**Comment by sanchojaf** [comment]
Also the cURL for retrive schedulers work fine to me

```bath
curl -X GET \
      -H 'X-User-Access-Key: XXXXXX' \
      -H 'X-User-Access-Token: YYYYYYYYYY' \
      -H 'Content-Type: application/json' \
      -d '{"page":1,"limit":25,"order":"id"}' \
      'https://cenit.io/api/v2/setup/scheduler.json' 
```

```
{"total_pages":1,"current_page":1,"count":5,"schedulers":[{"id":"2","namespace":"test","name":"a902102","expression":{"start_at":"2017-05-10","end_at":"2017-05-10","type":"cyclic","cyclic_expression":"1d"},"activated":false},{"id":"591378bf25d9856ed800040a","namespace":"test","name":"a90210","expression":{"start_at":"2017-05-10","end_at":"2017-05-10","type":"cyclic","cyclic_expression":"1d"},"activated":false},{"id":"5913792b25d9856ee2000602","namespace":"test","name":"a902101","expression":{"start_at":"2017-05-10","end_at":"2017-05-10","type":"cyclic","cyclic_expression":"1d"},"activated":false},{"id":"575184f7ad9815472c000123","namespace":"Administration","name":"Every 1h","expression":{"type":"cyclic","cyclic_expression":"1h"},"activated":true},{"id":"57bf4f5bad98150b18000195","namespace":"Administration","name":"Every 8h","expression":{"type":"cyclic","cyclic_expression":"8h"},"activated":true}]}        
```

**Comment by sanchojaf** [comment]
Hi @dataf3l Was possible for you to verify if is working well?. thank

**Comment by dataf3l** [comment]
@sanchojaf, Curl works, however the issue was the ruby example code didn't work, the examples should work in all languages, no?

**Comment by sanchojaf** [comment]
@dataf3l, yes sure! then we need review each language.

**Comment by sanchojaf** [comment]
Hi @dataf3l 

I find the issue with `Ruby`, The data to send need to be called a `payload`, then we need to remove the `params` line.
 
```Ruby
response = RestClient::Request.execute(
  :url => "https://cenit.io/api/v2/setup/scheduler.json",
  :method => 'POST',
  :headers => {
    'Content-Type' => 'application/json',
    'X-User-Access-Key' => user_access_key,
    'X-User-Access-Token' => user_access_token,
    'params' => {"id":"","namespace":"","name":"","_type":"","expression":{},"activated":""}
  }
)
```

and then add `payload`

```Ruby
response = RestClient::Request.execute(
  :url => "https://cenit.io/api/v2/setup/scheduler.json",
  :method => 'POST',
  :payload => '{"id":"","namespace":"","name":"","_type":"","expression":{},"activated":""}',
  :headers => {
    'Content-Type' => 'application/json',
    'X-User-Access-Key' => user_access_key,
    'X-User-Access-Token' => user_access_token,
  }
)
```

for example the next code

```Ruby
require 'rest-client'
require 'json'

user_access_key = 'XXXXXX'
user_access_token = 'YYYYYYYY'

response = RestClient::Request.execute(
  :url => "https://cenit.io/api/v2/setup/scheduler.json",
  :method => 'POST',
  :payload => '{"namespace":"test","name":"a902asasasassasas02","_type":"","expression":{"start_at":"2017-05-10","end_at":"2017-05-10","type":"cyclic","cyclic_expression":"1d"},"activated":""}',
  :headers => {
    'Content-Type' => 'application/json',
    'X-User-Access-Key' => user_access_key,
    'X-User-Access-Token' => user_access_token
  }
)
   

puts JSON.parse(response.body)
```

return a valid a success response:

```
{"success"=>{"scheduler"=>{"id"=>"5916529d25d985324b000382", "namespace"=>"test", "name"=>"a902asasasassasas02", "expression"=>{"start_at"=>"2017-05-10", "end_at"=>"2017-05-10", "type"=>"cyclic", "cyclic_expression"=>"1d"}, "activated"=>false}}}
```

**Comment by sanchojaf** [comment]
@dataf3l merged in develop the fix

**Comment by sanchojaf** [comment]
Was deployed to master !
