### ISSUE TITLE
Mautic Integration

### ISSUE THREAD

**Issue by Kyle-Foley** [cenit-io/cenit#1500]
## Context

Mautic is a new, open-source marketing automation platform.

It would be great if you could integrate the backend of [Mautic](www.mautic.org) with the many other applications already featured in Cenit.io.

[Here is a link](https://developer.mautic.org/) to their developer documentation.

**Comment by sanchojaf** [comment]
Thanks for the recommendation @	Kyle-Foley, for sure we will review Mautic

**Comment by Kyle-Foley** [comment]
@sanchojaf Also, clicking any sidebar links on your website gives me a Heroku application error.

[Example](https://cenit-portal.herokuapp.com/prices)

**Comment by sanchojaf** [comment]
Thanks, Yes this page a free heroku page, and we waste the resource for the current month yesterday, that will be working back tomorrow June 1st.

Our main website is http://cenit.io/
