### ISSUE TITLE
More specs and CI is required

### ISSUE THREAD

**Issue by nebtrx** [cenit-io/cenit#1557]
Nice piece of work guys. In order to lure more devs into this project and a build a community around it you should really add more specs and CI integration. The specs topic is critical right now as the test coverage is really low. Is very common to find a Rails project with more spec LOC than production LOC.
Good luck and keep it up with the hard work.

**Comment by sanchojaf** [comment]
Thank @nebtrx for your feedback, you are right that is an important area that we need improve.
