### ISSUE TITLE
Can't Buil App on Heroku

### ISSUE THREAD

**Issue by kintaro1981** [cenit-io/cenit#1809]
I'm trying to build cenit on Heroku (free) but I can't.

Here's the log:
https://pastebin.com/Us8yrUHP

**Comment by sanchojaf** [comment]
Hello @kintaro1981 thank for report the issue, 

Was fixed by @yoandrypa, in the next commits: 
- 4f2e658e75bc9339f9ae510c1a19800b8fbad90c 
- e197c5c3dca36b0ef65d6966ccba8734517bdae0.
