### ISSUE TITLE
Not found any help

### ISSUE THREAD

**Issue by W360S** [cenit-io/cenit#2050]
hello, it looks like no docs, nobody maintains for this project

**Comment by sanchojaf** [comment]
Hello @W360S the project is active, has a slack channel and a contact us on the website. please let us now how we can help you. 

Best,
Miguel

**Comment by W360S** [comment]
i try via slack, other channel no response

**Comment by W360S** [comment]
i want to post request from out side to create record with json code. can it do that?

**Comment by W360S** [comment]
similiar like that: https://docs.google.com/forms/d/e/1FAIpQLSflJsxXRZ9abI_FIdvxE9zSL4sWdBFH6uWOjhnIyHc8wPA_Vw/formResponse?usp=pp_url&entry.829045955={{request_title}}&entry.666998494={{fullname}}&entry.122816137={{email}}&entry.2107351628={{phone}}&entry.744394025={{Noted}}
