### ISSUE TITLE
Got strange error alfter pulled Woocommerce collection

### ISSUE THREAD

**Issue by bwx** [cenit-io/cenit#2400]
After installing cenit.io (step  by step following instructions, on Ubuntu 16) we pulled woocommerce collection 0.0.1. then we 'vr to install but got these error:
`Shared Collection failed to be pulled
- An unexpected error occurs ( message: Attempted to set a value for 'refresh_token_strategy' which is not allowed on the model Setup::AuthorizationProvider. summary: Without including Mongoid::Attributes::Dynamic in your model and the attribute does not already exist in the attributes hash, attempting to call Setup::AuthorizationProvider#refresh_token_strategy= for it is not allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and is raised in...`
## Context
Setup Woocommerce collection on selfinstalled instance. after push pull button got

> Shared Collection failed to be pulled

Tried with changes in config/mongoid.yml
`defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: false`
  still no success

## Expected Behavior
Shared Collection failed to be pulled
- An unexpected error occurs ( message: Attempted to set a value for 'refresh_token_strategy' which is not allowed on the model Setup::AuthorizationProvider. summary: Without including Mongoid::Attributes::Dynamic in your model and the attribute does not already exist in the attributes hash, attempting to call Setup::AuthorizationProvider#refresh_token_strategy= for it is not allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and is raised in...

## Actual Behavior
Install Collection

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

**Comment by macarci** [comment]
Hi @bwx I suppose got the WooCommerce collection through the remote shared collection connector. Please delete your local WooCommerce shared collection and try to pull it again, there was an error with the collection metadata. Le us know if the error persist!

**Comment by bwx** [comment]
I'ts OK :) many thanks !!!!
