### ISSUE TITLE
docker-compose asks for NRIA_LICENSE_KEY and the frontend exits

### ISSUE THREAD

**Issue by romanxts** [cenit-io/cenit#2843]
## Context
Using docker-compose doesn't bring up the system

I just want to run it locally for evaluation

## Expected Behavior
I would have expected to be able to connect with my browser after running docker-compose

## Actual Behavior
The frontend exits saying

level=fatal msg="can't load configuration file" error="no license key set. Please add the license to the agent's configuration file or NRIA_LICENSE_KEY environment variable"

## Steps to Reproduce
docker-compose -f docker-compose.yml up

## Your Environment
MacOS Catalina using the dock-compose file in the repo

**Comment by TFAssKID** [comment]
@romanxts this is because we was create the container using an [New Relic image](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring/) base try using our docker image without New Relic - ```cenitgroup/cenitio:backend```
