### ISSUE TITLE
what is peddler used for?

### ISSUE THREAD

**Issue by masavini** [cenit-io/cenit#2867]
hi,
i'm looking forward for an integration with amazon mws api.
i see cenit has [https://github.com/hakanensari/peddler](url) among dependencies, but i can't find any info about amazon mws api integration in cenit documentation...

is such an integration already available, just a plan for the future or anything else?

**Comment by sanchojaf** [comment]
Hi, 
Yes, the dependency was added to build a custom integration with Amazon MWS API.

If you are still interested in this please send us an email to support@cenit.io

Thanks
